CREATE TABLE ALUMNO 
(
  ID NUMBER NOT NULL 
, APELLIDOS VARCHAR2(20) 
, NOMBRES VARCHAR2(20) 
, CONSTRAINT ALUMNO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE ALUMNO_SEQ1;

CREATE TRIGGER ALUMNO_TRG 
BEFORE INSERT ON ALUMNO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ALUMNO_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
