CREATE TABLE CARRERA 
(
  ID NUMBER NOT NULL 
, NOMBRECARRE VARCHAR2(20) 
, DURACION VARCHAR2(20) 
, CONSTRAINT CARRERA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE CARRERA_SEQ;

CREATE TRIGGER CARRERA_TRG 
BEFORE INSERT ON CARRERA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CARRERA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
